/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using Newtonsoft.Json;
using System;
using System.Runtime.Serialization;
using System.Text;

namespace Ingenico.Direct.Fake.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class AdditionalOrderInput : IEquatable<AdditionalOrderInput>
    {
        /// <summary>
        /// Gets or Sets AirlineData
        /// </summary>
        [DataMember(Name = "airlineData")]
        public AirlineData AirlineData { get; set; }

        /// <summary>
        /// Gets or Sets Level3SummaryData
        /// </summary>
        [DataMember(Name = "level3SummaryData")]
        public Level3SummaryData Level3SummaryData { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfInstallments
        /// </summary>
        [DataMember(Name = "numberOfInstallments")]
        public long? NumberOfInstallments { get; set; }

        /// <summary>
        /// Gets or Sets OrderDate
        /// </summary>
        [DataMember(Name = "orderDate")]
        public string OrderDate { get; set; }

        /// <summary>
        /// Gets or Sets TypeInformation
        /// </summary>
        [DataMember(Name = "typeInformation")]
        public OrderTypeInformation TypeInformation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdditionalOrderInput {\n");
            sb.Append("  AirlineData: ").Append(AirlineData).Append("\n");
            sb.Append("  Level3SummaryData: ").Append(Level3SummaryData).Append("\n");
            sb.Append("  NumberOfInstallments: ").Append(NumberOfInstallments).Append("\n");
            sb.Append("  OrderDate: ").Append(OrderDate).Append("\n");
            sb.Append("  TypeInformation: ").Append(TypeInformation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((AdditionalOrderInput)obj);
        }

        /// <summary>
        /// Returns true if AdditionalOrderInput instances are equal
        /// </summary>
        /// <param name="other">Instance of AdditionalOrderInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdditionalOrderInput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    AirlineData == other.AirlineData ||
                    AirlineData != null &&
                    AirlineData.Equals(other.AirlineData)
                ) &&
                (
                    Level3SummaryData == other.Level3SummaryData ||
                    Level3SummaryData != null &&
                    Level3SummaryData.Equals(other.Level3SummaryData)
                ) &&
                (
                    NumberOfInstallments == other.NumberOfInstallments ||
                    NumberOfInstallments != null &&
                    NumberOfInstallments.Equals(other.NumberOfInstallments)
                ) &&
                (
                    OrderDate == other.OrderDate ||
                    OrderDate != null &&
                    OrderDate.Equals(other.OrderDate)
                ) &&
                (
                    TypeInformation == other.TypeInformation ||
                    TypeInformation != null &&
                    TypeInformation.Equals(other.TypeInformation)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (AirlineData != null)
                    hashCode = hashCode * 59 + AirlineData.GetHashCode();
                if (Level3SummaryData != null)
                    hashCode = hashCode * 59 + Level3SummaryData.GetHashCode();
                if (NumberOfInstallments != null)
                    hashCode = hashCode * 59 + NumberOfInstallments.GetHashCode();
                if (OrderDate != null)
                    hashCode = hashCode * 59 + OrderDate.GetHashCode();
                if (TypeInformation != null)
                    hashCode = hashCode * 59 + TypeInformation.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(AdditionalOrderInput left, AdditionalOrderInput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(AdditionalOrderInput left, AdditionalOrderInput right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
