/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Ingenico.Direct.Fake.Models
{ 
    /// <summary>
    /// Results of Fraugster fraud prevention check. Fraugster collects transaction data points such as name, email address, billing, etc. to analyze whether or not the transaction is fraudulent.
    /// </summary>
    [DataContract]
    public partial class FraugsterResults : IEquatable<FraugsterResults>
    { 
        /// <summary>
        /// Result of the Fraugster check Contains the investigation points used during the evaluation
        /// </summary>
        /// <value>Result of the Fraugster check Contains the investigation points used during the evaluation</value>
        [DataMember(Name="fraudInvestigationPoints")]
        public string FraudInvestigationPoints { get; set; }

        /// <summary>
        /// Result of the Fraugster check Contains the overall Fraud score which is an integer between 0 and 99
        /// </summary>
        /// <value>Result of the Fraugster check Contains the overall Fraud score which is an integer between 0 and 99</value>
        [DataMember(Name="fraudScore")]
        public int? FraudScore { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FraugsterResults {\n");
            sb.Append("  FraudInvestigationPoints: ").Append(FraudInvestigationPoints).Append("\n");
            sb.Append("  FraudScore: ").Append(FraudScore).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((FraugsterResults)obj);
        }

        /// <summary>
        /// Returns true if FraugsterResults instances are equal
        /// </summary>
        /// <param name="other">Instance of FraugsterResults to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FraugsterResults other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FraudInvestigationPoints == other.FraudInvestigationPoints ||
                    FraudInvestigationPoints != null &&
                    FraudInvestigationPoints.Equals(other.FraudInvestigationPoints)
                ) && 
                (
                    FraudScore == other.FraudScore ||
                    FraudScore != null &&
                    FraudScore.Equals(other.FraudScore)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FraudInvestigationPoints != null)
                    hashCode = hashCode * 59 + FraudInvestigationPoints.GetHashCode();
                    if (FraudScore != null)
                    hashCode = hashCode * 59 + FraudScore.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(FraugsterResults left, FraugsterResults right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(FraugsterResults left, FraugsterResults right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
