/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Ingenico.Direct.Fake.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class OrderStatusOutput : IEquatable<OrderStatusOutput>
    { 
        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name="errors")]
        public List<APIError> Errors { get; set; }

        /// <summary>
        /// Flag indicating if the payment can be cancelled   * true   * false
        /// </summary>
        /// <value>Flag indicating if the payment can be cancelled   * true   * false</value>
        [DataMember(Name="isCancellable")]
        public bool? IsCancellable { get; set; }

        /// <summary>
        /// Highlevel status of the payment, payout or refund.   Please see Statuses for a full overview of possible values.
        /// </summary>
        /// <value>Highlevel status of the payment, payout or refund.   Please see Statuses for a full overview of possible values.</value>
        [DataMember(Name="statusCategory")]
        public string StatusCategory { get; set; }

        /// <summary>
        /// Numeric status code of the legacy API. It is returned to ease the migration from the legacy APIs. You should not write new business logic based on this property as it will be deprecated in a future version of the API. The value can also be found in the in the BackOffice and in report files.
        /// </summary>
        /// <value>Numeric status code of the legacy API. It is returned to ease the migration from the legacy APIs. You should not write new business logic based on this property as it will be deprecated in a future version of the API. The value can also be found in the in the BackOffice and in report files.</value>
        [DataMember(Name="statusCode")]
        public int? StatusCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderStatusOutput {\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("  IsCancellable: ").Append(IsCancellable).Append("\n");
            sb.Append("  StatusCategory: ").Append(StatusCategory).Append("\n");
            sb.Append("  StatusCode: ").Append(StatusCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((OrderStatusOutput)obj);
        }

        /// <summary>
        /// Returns true if OrderStatusOutput instances are equal
        /// </summary>
        /// <param name="other">Instance of OrderStatusOutput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderStatusOutput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Errors == other.Errors ||
                    Errors != null &&
                    Errors.SequenceEqual(other.Errors)
                ) && 
                (
                    IsCancellable == other.IsCancellable ||
                    IsCancellable != null &&
                    IsCancellable.Equals(other.IsCancellable)
                ) && 
                (
                    StatusCategory == other.StatusCategory ||
                    StatusCategory != null &&
                    StatusCategory.Equals(other.StatusCategory)
                ) && 
                (
                    StatusCode == other.StatusCode ||
                    StatusCode != null &&
                    StatusCode.Equals(other.StatusCode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Errors != null)
                    hashCode = hashCode * 59 + Errors.GetHashCode();
                    if (IsCancellable != null)
                    hashCode = hashCode * 59 + IsCancellable.GetHashCode();
                    if (StatusCategory != null)
                    hashCode = hashCode * 59 + StatusCategory.GetHashCode();
                    if (StatusCode != null)
                    hashCode = hashCode * 59 + StatusCode.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(OrderStatusOutput left, OrderStatusOutput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(OrderStatusOutput left, OrderStatusOutput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
