/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Ingenico.Direct.Fake.Models
{ 
    /// <summary>
    /// Object that holds all reference properties that are linked to this transaction
    /// </summary>
    [DataContract]
    public partial class PaymentReferences : IEquatable<PaymentReferences>
    { 
        /// <summary>
        /// Your unique reference of the transaction that is also returned in our report files. This is almost always used for your reconciliation of our report files.
        /// </summary>
        /// <value>Your unique reference of the transaction that is also returned in our report files. This is almost always used for your reconciliation of our report files.</value>
        [DataMember(Name="merchantReference")]
        public string MerchantReference { get; set; }

        /// <summary>
        /// When you did not supply a merchantReference for your payment, you need to fill this property with the reference of the original payment when you want to refund it
        /// </summary>
        /// <value>When you did not supply a merchantReference for your payment, you need to fill this property with the reference of the original payment when you want to refund it</value>
        [DataMember(Name="referenceOrigPayment")]
        public string ReferenceOrigPayment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentReferences {\n");
            sb.Append("  MerchantReference: ").Append(MerchantReference).Append("\n");
            sb.Append("  ReferenceOrigPayment: ").Append(ReferenceOrigPayment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaymentReferences)obj);
        }

        /// <summary>
        /// Returns true if PaymentReferences instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentReferences to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentReferences other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MerchantReference == other.MerchantReference ||
                    MerchantReference != null &&
                    MerchantReference.Equals(other.MerchantReference)
                ) && 
                (
                    ReferenceOrigPayment == other.ReferenceOrigPayment ||
                    ReferenceOrigPayment != null &&
                    ReferenceOrigPayment.Equals(other.ReferenceOrigPayment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MerchantReference != null)
                    hashCode = hashCode * 59 + MerchantReference.GetHashCode();
                    if (ReferenceOrigPayment != null)
                    hashCode = hashCode * 59 + ReferenceOrigPayment.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaymentReferences left, PaymentReferences right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaymentReferences left, PaymentReferences right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
