/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Ingenico.Direct.Fake.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaymentProduct840CustomerAccount : IEquatable<PaymentProduct840CustomerAccount>
    { 
        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name="accountId")]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets BillingAgreementId
        /// </summary>
        [DataMember(Name="billingAgreementId")]
        public string BillingAgreementId { get; set; }

        /// <summary>
        /// Gets or Sets CompanyName
        /// </summary>
        [DataMember(Name="companyName")]
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or Sets CountryCode
        /// </summary>
        [DataMember(Name="countryCode")]
        public string CountryCode { get; set; }

        /// <summary>
        /// Gets or Sets CustomerAccountStatus
        /// </summary>
        [DataMember(Name="customerAccountStatus")]
        public string CustomerAccountStatus { get; set; }

        /// <summary>
        /// Gets or Sets CustomerAddressStatus
        /// </summary>
        [DataMember(Name="customerAddressStatus")]
        public string CustomerAddressStatus { get; set; }

        /// <summary>
        /// Gets or Sets FirstName
        /// </summary>
        [DataMember(Name="firstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// Gets or Sets PayerId
        /// </summary>
        [DataMember(Name="payerId")]
        public string PayerId { get; set; }

        /// <summary>
        /// Gets or Sets Surname
        /// </summary>
        [DataMember(Name="surname")]
        public string Surname { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentProduct840CustomerAccount {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  BillingAgreementId: ").Append(BillingAgreementId).Append("\n");
            sb.Append("  CompanyName: ").Append(CompanyName).Append("\n");
            sb.Append("  CountryCode: ").Append(CountryCode).Append("\n");
            sb.Append("  CustomerAccountStatus: ").Append(CustomerAccountStatus).Append("\n");
            sb.Append("  CustomerAddressStatus: ").Append(CustomerAddressStatus).Append("\n");
            sb.Append("  FirstName: ").Append(FirstName).Append("\n");
            sb.Append("  PayerId: ").Append(PayerId).Append("\n");
            sb.Append("  Surname: ").Append(Surname).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaymentProduct840CustomerAccount)obj);
        }

        /// <summary>
        /// Returns true if PaymentProduct840CustomerAccount instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentProduct840CustomerAccount to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentProduct840CustomerAccount other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AccountId == other.AccountId ||
                    AccountId != null &&
                    AccountId.Equals(other.AccountId)
                ) && 
                (
                    BillingAgreementId == other.BillingAgreementId ||
                    BillingAgreementId != null &&
                    BillingAgreementId.Equals(other.BillingAgreementId)
                ) && 
                (
                    CompanyName == other.CompanyName ||
                    CompanyName != null &&
                    CompanyName.Equals(other.CompanyName)
                ) && 
                (
                    CountryCode == other.CountryCode ||
                    CountryCode != null &&
                    CountryCode.Equals(other.CountryCode)
                ) && 
                (
                    CustomerAccountStatus == other.CustomerAccountStatus ||
                    CustomerAccountStatus != null &&
                    CustomerAccountStatus.Equals(other.CustomerAccountStatus)
                ) && 
                (
                    CustomerAddressStatus == other.CustomerAddressStatus ||
                    CustomerAddressStatus != null &&
                    CustomerAddressStatus.Equals(other.CustomerAddressStatus)
                ) && 
                (
                    FirstName == other.FirstName ||
                    FirstName != null &&
                    FirstName.Equals(other.FirstName)
                ) && 
                (
                    PayerId == other.PayerId ||
                    PayerId != null &&
                    PayerId.Equals(other.PayerId)
                ) && 
                (
                    Surname == other.Surname ||
                    Surname != null &&
                    Surname.Equals(other.Surname)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AccountId != null)
                    hashCode = hashCode * 59 + AccountId.GetHashCode();
                    if (BillingAgreementId != null)
                    hashCode = hashCode * 59 + BillingAgreementId.GetHashCode();
                    if (CompanyName != null)
                    hashCode = hashCode * 59 + CompanyName.GetHashCode();
                    if (CountryCode != null)
                    hashCode = hashCode * 59 + CountryCode.GetHashCode();
                    if (CustomerAccountStatus != null)
                    hashCode = hashCode * 59 + CustomerAccountStatus.GetHashCode();
                    if (CustomerAddressStatus != null)
                    hashCode = hashCode * 59 + CustomerAddressStatus.GetHashCode();
                    if (FirstName != null)
                    hashCode = hashCode * 59 + FirstName.GetHashCode();
                    if (PayerId != null)
                    hashCode = hashCode * 59 + PayerId.GetHashCode();
                    if (Surname != null)
                    hashCode = hashCode * 59 + Surname.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaymentProduct840CustomerAccount left, PaymentProduct840CustomerAccount right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaymentProduct840CustomerAccount left, PaymentProduct840CustomerAccount right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
