/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Ingenico.Direct.Fake.Models
{ 
    /// <summary>
    /// Object containing the details of the created payment.
    /// </summary>
    [DataContract]
    public partial class PaymentCreationOutput : PaymentCreationReferences, IEquatable<PaymentCreationOutput>
    { 
        /// <summary>
        /// Indicates if a new token was created   * true - A new token was created   * false - A token with the same card number already exists and is returned. Please note that the existing token has not been updated. When you want to update other data then the card number, you need to update data stored in the token explicitly, as data is never updated during the creation of a token.
        /// </summary>
        /// <value>Indicates if a new token was created   * true - A new token was created   * false - A token with the same card number already exists and is returned. Please note that the existing token has not been updated. When you want to update other data then the card number, you need to update data stored in the token explicitly, as data is never updated during the creation of a token.</value>
        [DataMember(Name="isNewToken")]
        public bool? IsNewToken { get; set; }

        /// <summary>
        /// ID of the token. This property is populated when the payment was done with a token or when the payment was tokenized.
        /// </summary>
        /// <value>ID of the token. This property is populated when the payment was done with a token or when the payment was tokenized.</value>
        [DataMember(Name="token")]
        public string Token { get; set; }

        /// <summary>
        /// Indicates if tokenization was successful or not. If this value is false, then the token and isNewToken properties will not be set.
        /// </summary>
        /// <value>Indicates if tokenization was successful or not. If this value is false, then the token and isNewToken properties will not be set.</value>
        [DataMember(Name="tokenizationSucceeded")]
        public bool? TokenizationSucceeded { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentCreationOutput {\n");
            sb.Append("  IsNewToken: ").Append(IsNewToken).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("  TokenizationSucceeded: ").Append(TokenizationSucceeded).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaymentCreationOutput)obj);
        }

        /// <summary>
        /// Returns true if PaymentCreationOutput instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentCreationOutput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentCreationOutput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    IsNewToken == other.IsNewToken ||
                    IsNewToken != null &&
                    IsNewToken.Equals(other.IsNewToken)
                ) && 
                (
                    Token == other.Token ||
                    Token != null &&
                    Token.Equals(other.Token)
                ) && 
                (
                    TokenizationSucceeded == other.TokenizationSucceeded ||
                    TokenizationSucceeded != null &&
                    TokenizationSucceeded.Equals(other.TokenizationSucceeded)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (IsNewToken != null)
                    hashCode = hashCode * 59 + IsNewToken.GetHashCode();
                    if (Token != null)
                    hashCode = hashCode * 59 + Token.GetHashCode();
                    if (TokenizationSucceeded != null)
                    hashCode = hashCode * 59 + TokenizationSucceeded.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaymentCreationOutput left, PaymentCreationOutput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaymentCreationOutput left, PaymentCreationOutput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
