/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Ingenico.Direct.Fake.Models
{ 
    /// <summary>
    /// Object containing the specific input details for payments that involve redirects to 3rd parties to complete, like PayPal
    /// </summary>
    [DataContract]
    public partial class RedirectPaymentMethodSpecificInput : AbstractRedirectPaymentMethodSpecificInput, IEquatable<RedirectPaymentMethodSpecificInput>
    { 
        /// <summary>
        /// Gets or Sets IsRecurring
        /// </summary>
        [DataMember(Name="isRecurring")]
        public bool? IsRecurring { get; set; }

        /// <summary>
        /// Gets or Sets PaymentProduct840SpecificInput
        /// </summary>
        [DataMember(Name="paymentProduct840SpecificInput")]
        public RedirectPaymentProduct840SpecificInput PaymentProduct840SpecificInput { get; set; }

        /// <summary>
        /// Gets or Sets ReturnUrl
        /// </summary>
        [DataMember(Name="returnUrl")]
        public string ReturnUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RedirectPaymentMethodSpecificInput {\n");
            sb.Append("  IsRecurring: ").Append(IsRecurring).Append("\n");
            sb.Append("  PaymentProduct840SpecificInput: ").Append(PaymentProduct840SpecificInput).Append("\n");
            sb.Append("  ReturnUrl: ").Append(ReturnUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RedirectPaymentMethodSpecificInput)obj);
        }

        /// <summary>
        /// Returns true if RedirectPaymentMethodSpecificInput instances are equal
        /// </summary>
        /// <param name="other">Instance of RedirectPaymentMethodSpecificInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RedirectPaymentMethodSpecificInput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    IsRecurring == other.IsRecurring ||
                    IsRecurring != null &&
                    IsRecurring.Equals(other.IsRecurring)
                ) && 
                (
                    PaymentProduct840SpecificInput == other.PaymentProduct840SpecificInput ||
                    PaymentProduct840SpecificInput != null &&
                    PaymentProduct840SpecificInput.Equals(other.PaymentProduct840SpecificInput)
                ) && 
                (
                    ReturnUrl == other.ReturnUrl ||
                    ReturnUrl != null &&
                    ReturnUrl.Equals(other.ReturnUrl)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (IsRecurring != null)
                    hashCode = hashCode * 59 + IsRecurring.GetHashCode();
                    if (PaymentProduct840SpecificInput != null)
                    hashCode = hashCode * 59 + PaymentProduct840SpecificInput.GetHashCode();
                    if (ReturnUrl != null)
                    hashCode = hashCode * 59 + ReturnUrl.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RedirectPaymentMethodSpecificInput left, RedirectPaymentMethodSpecificInput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RedirectPaymentMethodSpecificInput left, RedirectPaymentMethodSpecificInput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
