/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Ingenico.Direct.Fake.Models
{ 
    /// <summary>
    /// Object containing refund details
    /// </summary>
    [DataContract]
    public partial class RefundOutput : OrderOutput, IEquatable<RefundOutput>
    { 
        /// <summary>
        /// Gets or Sets CardRefundMethodSpecificOutput
        /// </summary>
        [DataMember(Name="cardRefundMethodSpecificOutput")]
        public RefundCardMethodSpecificOutput CardRefundMethodSpecificOutput { get; set; }

        /// <summary>
        /// Gets or Sets MobileRefundMethodSpecificOutput
        /// </summary>
        [DataMember(Name="mobileRefundMethodSpecificOutput")]
        public RefundMobileMethodSpecificOutput MobileRefundMethodSpecificOutput { get; set; }

        /// <summary>
        /// Gets or Sets EWalletRefundMethodSpecificOutput
        /// </summary>
        [DataMember(Name="eWalletRefundMethodSpecificOutput")]
        public RefundEWalletMethodSpecificOutput EWalletRefundMethodSpecificOutput { get; set; }

        /// <summary>
        /// Payment method identifier used by the our payment engine
        /// </summary>
        /// <value>Payment method identifier used by the our payment engine</value>
        [DataMember(Name="paymentMethod")]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RefundOutput {\n");
            sb.Append("  CardRefundMethodSpecificOutput: ").Append(CardRefundMethodSpecificOutput).Append("\n");
            sb.Append("  MobileRefundMethodSpecificOutput: ").Append(MobileRefundMethodSpecificOutput).Append("\n");
            sb.Append("  EWalletRefundMethodSpecificOutput: ").Append(EWalletRefundMethodSpecificOutput).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RefundOutput)obj);
        }

        /// <summary>
        /// Returns true if RefundOutput instances are equal
        /// </summary>
        /// <param name="other">Instance of RefundOutput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RefundOutput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CardRefundMethodSpecificOutput == other.CardRefundMethodSpecificOutput ||
                    CardRefundMethodSpecificOutput != null &&
                    CardRefundMethodSpecificOutput.Equals(other.CardRefundMethodSpecificOutput)
                ) && 
                (
                    MobileRefundMethodSpecificOutput == other.MobileRefundMethodSpecificOutput ||
                    MobileRefundMethodSpecificOutput != null &&
                    MobileRefundMethodSpecificOutput.Equals(other.MobileRefundMethodSpecificOutput)
                ) && 
                (
                    EWalletRefundMethodSpecificOutput == other.EWalletRefundMethodSpecificOutput ||
                    EWalletRefundMethodSpecificOutput != null &&
                    EWalletRefundMethodSpecificOutput.Equals(other.EWalletRefundMethodSpecificOutput)
                ) && 
                (
                    PaymentMethod == other.PaymentMethod ||
                    PaymentMethod != null &&
                    PaymentMethod.Equals(other.PaymentMethod)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CardRefundMethodSpecificOutput != null)
                    hashCode = hashCode * 59 + CardRefundMethodSpecificOutput.GetHashCode();
                    if (MobileRefundMethodSpecificOutput != null)
                    hashCode = hashCode * 59 + MobileRefundMethodSpecificOutput.GetHashCode();
                    if (EWalletRefundMethodSpecificOutput != null)
                    hashCode = hashCode * 59 + EWalletRefundMethodSpecificOutput.GetHashCode();
                    if (PaymentMethod != null)
                    hashCode = hashCode * 59 + PaymentMethod.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RefundOutput left, RefundOutput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RefundOutput left, RefundOutput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
