/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Ingenico.Direct.Fake.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RefundResult : AbstractOrderStatus, IEquatable<RefundResult>
    { 
        /// <summary>
        /// Gets or Sets RefundOutput
        /// </summary>
        [DataMember(Name="refundOutput")]
        public RefundOutput RefundOutput { get; set; }

        /// <summary>
        /// Current high-level status of the refund in a human-readable form.
        /// </summary>
        /// <value>Current high-level status of the refund in a human-readable form.</value>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// This object has the numeric representation of the current refund status, timestamp of last status change and performable action on the current refund resource.   In case of a rejected refund, detailed error information is listed.
        /// </summary>
        /// <value>This object has the numeric representation of the current refund status, timestamp of last status change and performable action on the current refund resource.   In case of a rejected refund, detailed error information is listed.</value>
        [DataMember(Name="statusOutput")]
        public OrderStatusOutput StatusOutput { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RefundResult {\n");
            sb.Append("  RefundOutput: ").Append(RefundOutput).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusOutput: ").Append(StatusOutput).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RefundResult)obj);
        }

        /// <summary>
        /// Returns true if RefundResult instances are equal
        /// </summary>
        /// <param name="other">Instance of RefundResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RefundResult other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    RefundOutput == other.RefundOutput ||
                    RefundOutput != null &&
                    RefundOutput.Equals(other.RefundOutput)
                ) && 
                (
                    Status == other.Status ||
                    Status != null &&
                    Status.Equals(other.Status)
                ) && 
                (
                    StatusOutput == other.StatusOutput ||
                    StatusOutput != null &&
                    StatusOutput.Equals(other.StatusOutput)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (RefundOutput != null)
                    hashCode = hashCode * 59 + RefundOutput.GetHashCode();
                    if (Status != null)
                    hashCode = hashCode * 59 + Status.GetHashCode();
                    if (StatusOutput != null)
                    hashCode = hashCode * 59 + StatusOutput.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RefundResult left, RefundResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RefundResult left, RefundResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
