/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class MandateSepaDirectDebit : IEquatable<MandateSepaDirectDebit>
    { 
        /// <summary>
        /// Gets or Sets Creditor
        /// </summary>
        [DataMember(Name="creditor")]
        public Creditor Creditor { get; set; }

        /// <summary>
        /// Gets or Sets MandateId
        /// </summary>
        [DataMember(Name="mandateId")]
        public string MandateId { get; set; }

        /// <summary>
        /// Gets or Sets BankAccountIban
        /// </summary>
        [DataMember(Name="bankAccountIban")]
        public BankAccountIban BankAccountIban { get; set; }

        /// <summary>
        /// Gets or Sets CustomerContractIdentifier
        /// </summary>
        [DataMember(Name="customerContractIdentifier")]
        public string CustomerContractIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets Debtor
        /// </summary>
        [DataMember(Name="debtor")]
        public Debtor Debtor { get; set; }

        /// <summary>
        /// Gets or Sets IsRecurring
        /// </summary>
        [DataMember(Name="isRecurring")]
        public bool? IsRecurring { get; set; }

        /// <summary>
        /// Gets or Sets MandateApproval
        /// </summary>
        [DataMember(Name="mandateApproval")]
        public MandateApproval MandateApproval { get; set; }

        /// <summary>
        /// Gets or Sets PreNotification
        /// </summary>
        [DataMember(Name="preNotification")]
        public string PreNotification { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MandateSepaDirectDebit {\n");
            sb.Append("  Creditor: ").Append(Creditor).Append("\n");
            sb.Append("  MandateId: ").Append(MandateId).Append("\n");
            sb.Append("  BankAccountIban: ").Append(BankAccountIban).Append("\n");
            sb.Append("  CustomerContractIdentifier: ").Append(CustomerContractIdentifier).Append("\n");
            sb.Append("  Debtor: ").Append(Debtor).Append("\n");
            sb.Append("  IsRecurring: ").Append(IsRecurring).Append("\n");
            sb.Append("  MandateApproval: ").Append(MandateApproval).Append("\n");
            sb.Append("  PreNotification: ").Append(PreNotification).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MandateSepaDirectDebit)obj);
        }

        /// <summary>
        /// Returns true if MandateSepaDirectDebit instances are equal
        /// </summary>
        /// <param name="other">Instance of MandateSepaDirectDebit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MandateSepaDirectDebit other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Creditor == other.Creditor ||
                    Creditor != null &&
                    Creditor.Equals(other.Creditor)
                ) && 
                (
                    MandateId == other.MandateId ||
                    MandateId != null &&
                    MandateId.Equals(other.MandateId)
                ) && 
                (
                    BankAccountIban == other.BankAccountIban ||
                    BankAccountIban != null &&
                    BankAccountIban.Equals(other.BankAccountIban)
                ) && 
                (
                    CustomerContractIdentifier == other.CustomerContractIdentifier ||
                    CustomerContractIdentifier != null &&
                    CustomerContractIdentifier.Equals(other.CustomerContractIdentifier)
                ) && 
                (
                    Debtor == other.Debtor ||
                    Debtor != null &&
                    Debtor.Equals(other.Debtor)
                ) && 
                (
                    IsRecurring == other.IsRecurring ||
                    IsRecurring != null &&
                    IsRecurring.Equals(other.IsRecurring)
                ) && 
                (
                    MandateApproval == other.MandateApproval ||
                    MandateApproval != null &&
                    MandateApproval.Equals(other.MandateApproval)
                ) && 
                (
                    PreNotification == other.PreNotification ||
                    PreNotification != null &&
                    PreNotification.Equals(other.PreNotification)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Creditor != null)
                    hashCode = hashCode * 59 + Creditor.GetHashCode();
                    if (MandateId != null)
                    hashCode = hashCode * 59 + MandateId.GetHashCode();
                    if (BankAccountIban != null)
                    hashCode = hashCode * 59 + BankAccountIban.GetHashCode();
                    if (CustomerContractIdentifier != null)
                    hashCode = hashCode * 59 + CustomerContractIdentifier.GetHashCode();
                    if (Debtor != null)
                    hashCode = hashCode * 59 + Debtor.GetHashCode();
                    if (IsRecurring != null)
                    hashCode = hashCode * 59 + IsRecurring.GetHashCode();
                    if (MandateApproval != null)
                    hashCode = hashCode * 59 + MandateApproval.GetHashCode();
                    if (PreNotification != null)
                    hashCode = hashCode * 59 + PreNotification.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MandateSepaDirectDebit left, MandateSepaDirectDebit right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MandateSepaDirectDebit left, MandateSepaDirectDebit right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
