/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaymentOutput : OrderOutput, IEquatable<PaymentOutput>
    { 
        /// <summary>
        /// Amount that has been paid
        /// </summary>
        /// <value>Amount that has been paid</value>
        [DataMember(Name="amountPaid")]
        public long? AmountPaid { get; set; }

        /// <summary>
        /// Gets or Sets CardPaymentMethodSpecificOutput
        /// </summary>
        [DataMember(Name="cardPaymentMethodSpecificOutput")]
        public CardPaymentMethodSpecificOutput CardPaymentMethodSpecificOutput { get; set; }

        /// <summary>
        /// Gets or Sets MobilePaymentMethodSpecificOutput
        /// </summary>
        [DataMember(Name="mobilePaymentMethodSpecificOutput")]
        public MobilePaymentMethodSpecificOutput MobilePaymentMethodSpecificOutput { get; set; }

        /// <summary>
        /// Payment method identifier used by the our payment engine.
        /// </summary>
        /// <value>Payment method identifier used by the our payment engine.</value>
        [DataMember(Name="paymentMethod")]
        public string PaymentMethod { get; set; }

        /// <summary>
        /// Gets or Sets RedirectPaymentMethodSpecificOutput
        /// </summary>
        [DataMember(Name="redirectPaymentMethodSpecificOutput")]
        public RedirectPaymentMethodSpecificOutput RedirectPaymentMethodSpecificOutput { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentOutput {\n");
            sb.Append("  AmountPaid: ").Append(AmountPaid).Append("\n");
            sb.Append("  CardPaymentMethodSpecificOutput: ").Append(CardPaymentMethodSpecificOutput).Append("\n");
            sb.Append("  MobilePaymentMethodSpecificOutput: ").Append(MobilePaymentMethodSpecificOutput).Append("\n");
            sb.Append("  PaymentMethod: ").Append(PaymentMethod).Append("\n");
            sb.Append("  RedirectPaymentMethodSpecificOutput: ").Append(RedirectPaymentMethodSpecificOutput).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaymentOutput)obj);
        }

        /// <summary>
        /// Returns true if PaymentOutput instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentOutput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentOutput other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AmountPaid == other.AmountPaid ||
                    AmountPaid != null &&
                    AmountPaid.Equals(other.AmountPaid)
                ) && 
                (
                    CardPaymentMethodSpecificOutput == other.CardPaymentMethodSpecificOutput ||
                    CardPaymentMethodSpecificOutput != null &&
                    CardPaymentMethodSpecificOutput.Equals(other.CardPaymentMethodSpecificOutput)
                ) && 
                (
                    MobilePaymentMethodSpecificOutput == other.MobilePaymentMethodSpecificOutput ||
                    MobilePaymentMethodSpecificOutput != null &&
                    MobilePaymentMethodSpecificOutput.Equals(other.MobilePaymentMethodSpecificOutput)
                ) && 
                (
                    PaymentMethod == other.PaymentMethod ||
                    PaymentMethod != null &&
                    PaymentMethod.Equals(other.PaymentMethod)
                ) && 
                (
                    RedirectPaymentMethodSpecificOutput == other.RedirectPaymentMethodSpecificOutput ||
                    RedirectPaymentMethodSpecificOutput != null &&
                    RedirectPaymentMethodSpecificOutput.Equals(other.RedirectPaymentMethodSpecificOutput)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AmountPaid != null)
                    hashCode = hashCode * 59 + AmountPaid.GetHashCode();
                    if (CardPaymentMethodSpecificOutput != null)
                    hashCode = hashCode * 59 + CardPaymentMethodSpecificOutput.GetHashCode();
                    if (MobilePaymentMethodSpecificOutput != null)
                    hashCode = hashCode * 59 + MobilePaymentMethodSpecificOutput.GetHashCode();
                    if (PaymentMethod != null)
                    hashCode = hashCode * 59 + PaymentMethod.GetHashCode();
                    if (RedirectPaymentMethodSpecificOutput != null)
                    hashCode = hashCode * 59 + RedirectPaymentMethodSpecificOutput.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaymentOutput left, PaymentOutput right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaymentOutput left, PaymentOutput right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
