/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Object containing display hints for this field, like the order, mask, preferred keyboard
    /// </summary>
    [DataContract]
    public partial class PaymentProductFieldDisplayHints : Dictionary<String, Object>, IEquatable<PaymentProductFieldDisplayHints>
    { 
        /// <summary>
        ///    * true - Indicates that this field is advised to be captured to increase the success rates even though it isn&#39;t marked as required. Please note that making the field required could hurt the success rates negatively. This boolean only indicates our advise to always show this field to the customer.   * false - Indicates that this field is not to be shown unless it is a required field.
        /// </summary>
        /// <value>   * true - Indicates that this field is advised to be captured to increase the success rates even though it isn&#39;t marked as required. Please note that making the field required could hurt the success rates negatively. This boolean only indicates our advise to always show this field to the customer.   * false - Indicates that this field is not to be shown unless it is a required field.</value>
        [DataMember(Name="alwaysShow")]
        public bool? AlwaysShow { get; set; }

        /// <summary>
        /// The order in which the fields should be shown (ascending)
        /// </summary>
        /// <value>The order in which the fields should be shown (ascending)</value>
        [DataMember(Name="displayOrder")]
        public int? DisplayOrder { get; set; }

        /// <summary>
        /// Gets or Sets FormElement
        /// </summary>
        [DataMember(Name="formElement")]
        public PaymentProductFieldFormElement FormElement { get; set; }

        /// <summary>
        /// Gets or Sets Label
        /// </summary>
        [DataMember(Name="label")]
        public string Label { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name="link")]
        public string Link { get; set; }

        /// <summary>
        /// Gets or Sets Mask
        /// </summary>
        [DataMember(Name="mask")]
        public string Mask { get; set; }

        /// <summary>
        /// Gets or Sets Obfuscate
        /// </summary>
        [DataMember(Name="obfuscate")]
        public bool? Obfuscate { get; set; }

        /// <summary>
        /// Gets or Sets PlaceholderLabel
        /// </summary>
        [DataMember(Name="placeholderLabel")]
        public string PlaceholderLabel { get; set; }

        /// <summary>
        /// Gets or Sets PreferredInputType
        /// </summary>
        [DataMember(Name="preferredInputType")]
        public string PreferredInputType { get; set; }

        /// <summary>
        /// Gets or Sets Tooltip
        /// </summary>
        [DataMember(Name="tooltip")]
        public PaymentProductFieldTooltip Tooltip { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentProductFieldDisplayHints {\n");
            sb.Append("  AlwaysShow: ").Append(AlwaysShow).Append("\n");
            sb.Append("  DisplayOrder: ").Append(DisplayOrder).Append("\n");
            sb.Append("  FormElement: ").Append(FormElement).Append("\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  Mask: ").Append(Mask).Append("\n");
            sb.Append("  Obfuscate: ").Append(Obfuscate).Append("\n");
            sb.Append("  PlaceholderLabel: ").Append(PlaceholderLabel).Append("\n");
            sb.Append("  PreferredInputType: ").Append(PreferredInputType).Append("\n");
            sb.Append("  Tooltip: ").Append(Tooltip).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaymentProductFieldDisplayHints)obj);
        }

        /// <summary>
        /// Returns true if PaymentProductFieldDisplayHints instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentProductFieldDisplayHints to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentProductFieldDisplayHints other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    AlwaysShow == other.AlwaysShow ||
                    AlwaysShow != null &&
                    AlwaysShow.Equals(other.AlwaysShow)
                ) && 
                (
                    DisplayOrder == other.DisplayOrder ||
                    DisplayOrder != null &&
                    DisplayOrder.Equals(other.DisplayOrder)
                ) && 
                (
                    FormElement == other.FormElement ||
                    FormElement != null &&
                    FormElement.Equals(other.FormElement)
                ) && 
                (
                    Label == other.Label ||
                    Label != null &&
                    Label.Equals(other.Label)
                ) && 
                (
                    Link == other.Link ||
                    Link != null &&
                    Link.Equals(other.Link)
                ) && 
                (
                    Mask == other.Mask ||
                    Mask != null &&
                    Mask.Equals(other.Mask)
                ) && 
                (
                    Obfuscate == other.Obfuscate ||
                    Obfuscate != null &&
                    Obfuscate.Equals(other.Obfuscate)
                ) && 
                (
                    PlaceholderLabel == other.PlaceholderLabel ||
                    PlaceholderLabel != null &&
                    PlaceholderLabel.Equals(other.PlaceholderLabel)
                ) && 
                (
                    PreferredInputType == other.PreferredInputType ||
                    PreferredInputType != null &&
                    PreferredInputType.Equals(other.PreferredInputType)
                ) && 
                (
                    Tooltip == other.Tooltip ||
                    Tooltip != null &&
                    Tooltip.Equals(other.Tooltip)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (AlwaysShow != null)
                    hashCode = hashCode * 59 + AlwaysShow.GetHashCode();
                    if (DisplayOrder != null)
                    hashCode = hashCode * 59 + DisplayOrder.GetHashCode();
                    if (FormElement != null)
                    hashCode = hashCode * 59 + FormElement.GetHashCode();
                    if (Label != null)
                    hashCode = hashCode * 59 + Label.GetHashCode();
                    if (Link != null)
                    hashCode = hashCode * 59 + Link.GetHashCode();
                    if (Mask != null)
                    hashCode = hashCode * 59 + Mask.GetHashCode();
                    if (Obfuscate != null)
                    hashCode = hashCode * 59 + Obfuscate.GetHashCode();
                    if (PlaceholderLabel != null)
                    hashCode = hashCode * 59 + PlaceholderLabel.GetHashCode();
                    if (PreferredInputType != null)
                    hashCode = hashCode * 59 + PreferredInputType.GetHashCode();
                    if (Tooltip != null)
                    hashCode = hashCode * 59 + Tooltip.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaymentProductFieldDisplayHints left, PaymentProductFieldDisplayHints right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaymentProductFieldDisplayHints left, PaymentProductFieldDisplayHints right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
