/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class PaymentProductFieldValidators : Dictionary<String, Object>, IEquatable<PaymentProductFieldValidators>
    { 
        /// <summary>
        /// Gets or Sets BoletoBancarioRequiredness
        /// </summary>
        [DataMember(Name="boletoBancarioRequiredness")]
        public BoletoBancarioRequirednessValidator BoletoBancarioRequiredness { get; set; }

        /// <summary>
        /// Gets or Sets EmailAddress
        /// </summary>
        [DataMember(Name="emailAddress")]
        public EmptyValidator EmailAddress { get; set; }

        /// <summary>
        /// Gets or Sets ExpirationDate
        /// </summary>
        [DataMember(Name="expirationDate")]
        public EmptyValidator ExpirationDate { get; set; }

        /// <summary>
        /// Gets or Sets FixedList
        /// </summary>
        [DataMember(Name="fixedList")]
        public FixedListValidator FixedList { get; set; }

        /// <summary>
        /// Gets or Sets Iban
        /// </summary>
        [DataMember(Name="iban")]
        public EmptyValidator Iban { get; set; }

        /// <summary>
        /// Gets or Sets Length
        /// </summary>
        [DataMember(Name="length")]
        public LengthValidator Length { get; set; }

        /// <summary>
        /// Gets or Sets Luhn
        /// </summary>
        [DataMember(Name="luhn")]
        public EmptyValidator Luhn { get; set; }

        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [DataMember(Name="range")]
        public RangeValidator Range { get; set; }

        /// <summary>
        /// Gets or Sets RegularExpression
        /// </summary>
        [DataMember(Name="regularExpression")]
        public RegularExpressionValidator RegularExpression { get; set; }

        /// <summary>
        /// Gets or Sets TermsAndConditions
        /// </summary>
        [DataMember(Name="termsAndConditions")]
        public EmptyValidator TermsAndConditions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentProductFieldValidators {\n");
            sb.Append("  BoletoBancarioRequiredness: ").Append(BoletoBancarioRequiredness).Append("\n");
            sb.Append("  EmailAddress: ").Append(EmailAddress).Append("\n");
            sb.Append("  ExpirationDate: ").Append(ExpirationDate).Append("\n");
            sb.Append("  FixedList: ").Append(FixedList).Append("\n");
            sb.Append("  Iban: ").Append(Iban).Append("\n");
            sb.Append("  Length: ").Append(Length).Append("\n");
            sb.Append("  Luhn: ").Append(Luhn).Append("\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("  RegularExpression: ").Append(RegularExpression).Append("\n");
            sb.Append("  TermsAndConditions: ").Append(TermsAndConditions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaymentProductFieldValidators)obj);
        }

        /// <summary>
        /// Returns true if PaymentProductFieldValidators instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentProductFieldValidators to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentProductFieldValidators other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BoletoBancarioRequiredness == other.BoletoBancarioRequiredness ||
                    BoletoBancarioRequiredness != null &&
                    BoletoBancarioRequiredness.Equals(other.BoletoBancarioRequiredness)
                ) && 
                (
                    EmailAddress == other.EmailAddress ||
                    EmailAddress != null &&
                    EmailAddress.Equals(other.EmailAddress)
                ) && 
                (
                    ExpirationDate == other.ExpirationDate ||
                    ExpirationDate != null &&
                    ExpirationDate.Equals(other.ExpirationDate)
                ) && 
                (
                    FixedList == other.FixedList ||
                    FixedList != null &&
                    FixedList.Equals(other.FixedList)
                ) && 
                (
                    Iban == other.Iban ||
                    Iban != null &&
                    Iban.Equals(other.Iban)
                ) && 
                (
                    Length == other.Length ||
                    Length != null &&
                    Length.Equals(other.Length)
                ) && 
                (
                    Luhn == other.Luhn ||
                    Luhn != null &&
                    Luhn.Equals(other.Luhn)
                ) && 
                (
                    Range == other.Range ||
                    Range != null &&
                    Range.Equals(other.Range)
                ) && 
                (
                    RegularExpression == other.RegularExpression ||
                    RegularExpression != null &&
                    RegularExpression.Equals(other.RegularExpression)
                ) && 
                (
                    TermsAndConditions == other.TermsAndConditions ||
                    TermsAndConditions != null &&
                    TermsAndConditions.Equals(other.TermsAndConditions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BoletoBancarioRequiredness != null)
                    hashCode = hashCode * 59 + BoletoBancarioRequiredness.GetHashCode();
                    if (EmailAddress != null)
                    hashCode = hashCode * 59 + EmailAddress.GetHashCode();
                    if (ExpirationDate != null)
                    hashCode = hashCode * 59 + ExpirationDate.GetHashCode();
                    if (FixedList != null)
                    hashCode = hashCode * 59 + FixedList.GetHashCode();
                    if (Iban != null)
                    hashCode = hashCode * 59 + Iban.GetHashCode();
                    if (Length != null)
                    hashCode = hashCode * 59 + Length.GetHashCode();
                    if (Luhn != null)
                    hashCode = hashCode * 59 + Luhn.GetHashCode();
                    if (Range != null)
                    hashCode = hashCode * 59 + Range.GetHashCode();
                    if (RegularExpression != null)
                    hashCode = hashCode * 59 + RegularExpression.GetHashCode();
                    if (TermsAndConditions != null)
                    hashCode = hashCode * 59 + TermsAndConditions.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaymentProductFieldValidators left, PaymentProductFieldValidators right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaymentProductFieldValidators left, PaymentProductFieldValidators right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
