/*
 * Ingenico Direct
 *
 *  # Introduction  The Ingenico Direct API has been designed as a REST API. It uses the HTTP protocol as its foundation. Each resource is accessible under a clearly named URL and the HTTP response codes are used to relay status. HTTP Verbs like GET and POST are used to interact with the resources. To support accessibility by clients directly, as opposed to your server, our servers support cross-origin resource sharing. We use JSON for all of our payloads, including error messages   All these characteristics mean that you will be able to use standard off the shelf software to interact with Ingenico ePayments. To make the integration even easier, Ingenico ePayments also has SDKs that wrap both the complete Server API as well as the complete Client API. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// Populated only when the actionType of the merchantAction is SHOW_FORM. In this case, this property contains the list of fields to render, in the format that is also used in the response of Get payment product.
    /// </summary>
    [DataContract]
    public partial class PaymentProductField : Dictionary<String, Object>, IEquatable<PaymentProductField>
    { 
        /// <summary>
        /// Gets or Sets DataRestrictions
        /// </summary>
        [DataMember(Name="dataRestrictions")]
        public PaymentProductFieldDataRestrictions DataRestrictions { get; set; }

        /// <summary>
        /// Gets or Sets DisplayHints
        /// </summary>
        [DataMember(Name="displayHints")]
        public PaymentProductFieldDisplayHints DisplayHints { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type")]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets UsedForLookup
        /// </summary>
        [DataMember(Name="usedForLookup")]
        public bool? UsedForLookup { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentProductField {\n");
            sb.Append("  DataRestrictions: ").Append(DataRestrictions).Append("\n");
            sb.Append("  DisplayHints: ").Append(DisplayHints).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  UsedForLookup: ").Append(UsedForLookup).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((PaymentProductField)obj);
        }

        /// <summary>
        /// Returns true if PaymentProductField instances are equal
        /// </summary>
        /// <param name="other">Instance of PaymentProductField to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentProductField other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    DataRestrictions == other.DataRestrictions ||
                    DataRestrictions != null &&
                    DataRestrictions.Equals(other.DataRestrictions)
                ) && 
                (
                    DisplayHints == other.DisplayHints ||
                    DisplayHints != null &&
                    DisplayHints.Equals(other.DisplayHints)
                ) && 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    UsedForLookup == other.UsedForLookup ||
                    UsedForLookup != null &&
                    UsedForLookup.Equals(other.UsedForLookup)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (DataRestrictions != null)
                    hashCode = hashCode * 59 + DataRestrictions.GetHashCode();
                    if (DisplayHints != null)
                    hashCode = hashCode * 59 + DisplayHints.GetHashCode();
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    if (UsedForLookup != null)
                    hashCode = hashCode * 59 + UsedForLookup.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(PaymentProductField left, PaymentProductField right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(PaymentProductField left, PaymentProductField right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
